# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: cd web && npm install
      - name: List
        run: cd web && npm run lint
      - name: Test
        run: cd web && npm run test:cov
      - name: Build
        run: cd web && npm build
        env:
          REACT_APP_SERVER_HOST: ${{ secrets.REACT_APP_SERVER_HOST }}
      - name: Store  code coverage results and dist
        uses: actions/upload-artifact@v2
        with:
          - name: dist
            path: web/build
          - name: code-coverage-report
            path: web/coverage